[[plugins]]
repo = 'Shougo/dein.vim'
[[plugins]] #カラーコード確認用 
repo = 'gorodinskiy/vim-coloresque'
#[[plugins]]#カラースキーム用*ただし、個々で設定するとvim-coloresqueがかき消されるので注意!
#repo = 'tomasr/molokai' #jacoborus/tender.vim
#hook_add = '''
#  set background=dark
#  " colorscheme 設定は source 後に行う必要があるので確実に読まれている VimEnter のタイミングで行う。
#  " 但し Colorscheme イベントの発生が抑制されないよう nented を付ける。
#  au MyAutoCmd VimEnter * nested colorscheme molokai
#'''
[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'
[[plugins]] #ステータスライン強化
repo = 'itchyny/lightline.vim'
[[plugins]] #ファイルツリー
repo = 'scrooloose/nerdtree'
[[plugins]] #コメントアウト用プラグイン <Leader>c<space>によりコメントアウト
repo = 'scrooloose/nerdcommenter'
hook_add  = '''
let g:NERDDefaultAlign = 'left'
let g:NERDSpaceDelims = 1
'''
