[[plugins]]
repo = 'Shougo/dein.vim'
#[[plugins]]
#repo = 'tomasr/molokai'
#hook_add = '''
#  set background=dark
#  syntax on
#  " colorscheme 設定は source 後に行う必要があるので確実に読まれている VimEnter のタイミングで行う。
#  " 但し Colorscheme イベントの発生が抑制されないよう nented を付ける。
#  au MyAutoCmd VimEnter * nested colorscheme molokai
#'''
[[plugins]]
repo = 'jacoborus/tender.vim'
hook_add = '''
  set background=dark
  syntax on
  " colorscheme 設定は source 後に行う必要があるので確実に読まれている VimEnter のタイミングで行う。
  " 但し Colorscheme イベントの発生が抑制されないよう nented を付ける。
  au MyAutoCmd VimEnter * nested colorscheme tender
'''
[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'
